name: firebase_auth_token
description: Extract user from verified Firebase Auth id token. The Firebase public key is cached and updated automatically.
homepage: https://github.com/Gerrel/firebase_auth_token
version: 1.0.7

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  http: ^1.2.2
  jose: ^0.3.4
  synchronized: ^3.3.0+1
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  
  
