name: firebase_auth_token
description: Extract user from verified Firebase Auth id token.
homepage: https://github.com/Gerrel/firebase_auth_token
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  jose: ^0.3.2
  synchronized: ^3.0.0
  
dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  
  
