name: firebase_auth_token
description: Extract user from verified Firebase Auth id token. The Firebase public key is cached and updated autimatically.
homepage: https://github.com/Gerrel/firebase_auth_token
version: 1.0.4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  jose: ^0.3.2
  synchronized: ^3.0.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  
  
